### ISSUE TITLE
Interactive config generator

### ISSUE THREAD

**Issue by droserasprout** [dipdup-net/dipdup#261]
**What feature would you like to see in DipDup?**

New command to start fresh DipDup project interactively.

**Why do you need this feature, what's the use case?**

Mostly for new projects. Optionally, to expand existing ones.

**Is there a workaround currently?**

Sorta, `cookiecutter` template.

**Comment by droserasprout** [comment]
It will be hard to keep env variables substitution in the generated config. And it's kinda essential. I suggest closing this one.

**Comment by m-kus** [comment]
Would be nice to have a built-in scaffolding tool though

**Comment by droserasprout** [comment]
Implemented in #495
