### ISSUE TITLE
Logs sent from within a hook are not shown in the stdout

### ISSUE THREAD

**Issue by m-kus** [dipdup-net/dipdup#520]
**Steps to reproduce:**

Use `HookContext.logger` to send info logs

**What did you expect to happen:**

Logs with `dipdup.hooks.*` context appear in stdout

**What actually happened:**

Logs are not shown

### Environment

* **Python version:** 3.10.1
* **DipDup version or commit hash:** 6.2.0
* **Database engine version:**
* **Hasura version:**
* **Are you in docker?** no
* **Can you reproduce this issue on `master`?**

**Comment by droserasprout** [comment]
To be honest, I'm not happy with `apscheduler` library. It's hard to configure, and we only use a bunch of its features.
